(function(){'use strict';
const D=window.STUDY_DATA, KEY='rutaDatos180_v1'; let db=load(), active=db.active&&db.users[db.active]?db.active:null, session=null;
const $=s=>document.querySelector(s), app=$('#app');
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{users:{},active:null}}catch(e){return{users:{},active:null}}}
function save(){db.active=active;localStorage.setItem(KEY,JSON.stringify(db))}
function user(){return db.users[active]}
function blank(name,start){return{name,start,created:new Date().toISOString(),days:{},stats:{answered:0,correct:0,byTopic:{},byQuestion:{}},review:{},vocab:{},exams:[],history:[],session:null,lastStudy:null}}
function esc(x){return String(x).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function dayNo(){let n=Math.floor((new Date(new Date().toDateString())-new Date(user().start+'T00:00:00'))/864e5)+1;return Math.max(1,Math.min(180,n))}
function ds(n=dayNo()){return user().days[n]||(user().days[n]={vocab:false,lesson:false,questions:false,evaluation:false,review:false})}
function completed(s){return s.vocab&&s.lesson&&s.questions&&s.evaluation&&(!dueReviews().length||s.review)}
function dueReviews(){let today=new Date().toISOString().slice(0,10);return Object.keys(user().review).filter(id=>user().review[id].due<=today)}
function addDays(n){let x=new Date();x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)}
function record(q,ok){let u=user(),t=u.stats.byTopic[q.topic]||(u.stats.byTopic[q.topic]={a:0,c:0});u.stats.answered++;t.a++;let p=u.stats.byQuestion[q.id]||(u.stats.byQuestion[q.id]={a:0,c:0});p.a++;if(ok){u.stats.correct++;t.c++;p.c++}let r=u.review[q.id]||{level:0,misses:0,due:addDays(1)};if(ok){r.level++;r.due=addDays([1,2,4,7,14,30][Math.min(r.level,5)]);if(r.level>=4)delete u.review[q.id];else u.review[q.id]=r}else{r.level=Math.max(0,r.level-1);r.misses++;r.due=addDays(r.misses>1?1:2);u.review[q.id]=r}u.lastStudy=new Date().toISOString().slice(0,10);save()}
function toast(x){$('#toast').textContent=x;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1700)}
function layout(title,body,sub=''){app.innerHTML=`<p class="eyebrow">${sub}</p><h1>${title}</h1>${body}`;app.focus()}
function ensure(){if(!active){users(true);return false}return true}
function users(force=false){let list=Object.entries(db.users).map(([id,u])=>`<div class="user"><span><strong>${esc(u.name)}</strong><br><small>Inicio: ${u.start}</small></span><button class="btn ${id===active?'secondary':''}" data-user="${id}">${id===active?'Activo':'Usar'}</button></div>`).join('');document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal" role="dialog" aria-modal="true"><section class="card"><h2>${list?'USUARIOS':'CREAR USUARIO DE ESTUDIO'}</h2>${list}<hr><h3>Crear otro usuario</h3><form id="userForm"><label>Nombre<br><input name="name" required maxlength="40" autocomplete="name"></label><br><label>Fecha en la que comienza a estudiar<br><input name="start" type="date" required value="${new Date().toISOString().slice(0,10)}"></label><p><button class="btn" type="submit">CREAR USUARIO</button> ${active&&!force?'<button class="btn ghost" type="button" id="closeModal">Cerrar</button>':''}</p></form></section></div>`);$('#userForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),id='u'+Date.now();db.users[id]=blank(f.get('name').trim(),f.get('start'));active=id;save();$('#modal').remove();home()};document.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>{active=b.dataset.user;save();$('#modal').remove();home()});if($('#closeModal'))$('#closeModal').onclick=()=>$('#modal').remove()}
function nextStep(){let s=ds();if(!s.vocab)return'vocabDaily';if(!s.lesson)return'lesson';if(!s.questions)return'learn';if(!s.evaluation)return'evaluation';if(dueReviews().length&&!s.review)return'review';return'home'}
function home(){if(!ensure())return;let n=dayNo(),d=D.days[n-1],s=ds(n),steps=[['vocab','Conceptos y vocabulario'],['lesson','Lección del día'],['questions','Preguntas de aprendizaje'],['evaluation','Evaluación corta'],['review','Revisar errores']];let st=steps.map(([k,label],i)=>{let required=k!=='review'||dueReviews().length,done=s[k]||!required;return`<button class="step ${done?'done':''}" data-step="${k}"><span class="num">${done?'✓':i+1}</span><span><strong>PASO ${i+1} · ${label}</strong><small>${required?'Actividad del día':'No hay repasos pendientes'}</small></span><span class="status">${done?'Completado ✓':'Pendiente'}</span></button>`}).join('');let resume=user().session?'<button class="btn ghost big" data-action="resume">CONTINUAR DONDE LO DEJÉ</button>':'';layout(`Hola, ${esc(user().name)}. Día ${n} / 180`,`<section class="hero"><p class="eyebrow">${d.phase}</p><h2>${d.topic}</h2><p>${d.subtopic}</p><div class="progressbar"><span style="width:${n/180*100}%"></span></div><p><span class="pill">${d.difficulty}</span> · ${d.module}</p></section><h2>EMPIEZA AQUÍ</h2>${st}<div class="toolbar"><button class="btn big" data-action="continue">${completed(s)?'DÍA COMPLETADO ✓':'CONTINUAR MI ESTUDIO'}</button>${resume}</div>`,'Tu ruta personalizada');bindHome()}
function bindHome(){document.querySelector('[data-action="continue"]').onclick=()=>go(nextStep());let r=document.querySelector('[data-action="resume"]');if(r)r.onclick=()=>resume();document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{let map={vocab:'vocabDaily',lesson:'lesson',questions:'learn',evaluation:'evaluation',review:'review'};go(map[b.dataset.step])})}
function vocabDaily(){let d=D.days[dayNo()-1],terms=d.terms.map(i=>D.terms[i]);layout('Vocabulario del día',terms.map(v=>`<article class="card"><p class="eyebrow">${v.category}</p><h2>${v.term}</h2><p><strong>Definición sencilla:</strong> ${v.definition}</p><p>${v.explanation}</p><p><strong>Ejemplo:</strong> ${v.example}</p><div class="toolbar"><button class="btn ghost speak" data-text="${esc(v.term+'. '+v.definition)}">🔊 ESCUCHAR</button><button class="btn ghost rate" data-id="${v.id}" data-rate="repeat">REPETIR</button><button class="btn ghost rate" data-id="${v.id}" data-rate="hard">DIFÍCIL</button><button class="btn secondary rate" data-id="${v.id}" data-rate="known">APRENDIDO</button></div></article>`).join('')+`<p><button class="btn big" id="vocabDone">CONTINUAR A LA LECCIÓN</button> <button class="btn ghost" id="vocabTest">EVALUACIÓN DE VOCABULARIO</button></p>`,'PASO 1');document.querySelectorAll('.speak').forEach(b=>b.onclick=()=>{speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(b.dataset.text))});document.querySelectorAll('.rate').forEach(b=>b.onclick=()=>{user().vocab[b.dataset.id]={rating:b.dataset.rate,date:new Date().toISOString()};save();toast('Autoevaluación guardada')});$('#vocabDone').onclick=()=>{ds().vocab=true;save();lesson()};$('#vocabTest').onclick=()=>startQuiz('vocab',vocabQuestions(),5,true)}
function lesson(){let d=D.days[dayNo()-1];layout(d.topic,`<article class="card">${d.lesson}</article><p><button class="btn big" id="lessonDone">CONTINUAR A PREGUNTAS</button></p>`,'PASO 2 · LECCIÓN DIARIA');$('#lessonDone').onclick=()=>{ds().lesson=true;save();startLearning()}}
function poolForDay(){let d=D.days[dayNo()-1],current=D.questions.filter(q=>q.topic===d.topic),due=dueReviews().map(id=>D.questions.find(q=>q.id===id)).filter(Boolean),general=D.questions.filter(q=>q.day<dayNo());return unique([...pick(current,6),...pick(due,3),...pick(general,2),...pick(D.questions,10)]).slice(0,10)}
function pick(a,n){return [...a].sort(()=>Math.random()-.5).slice(0,n)} function unique(a){return [...new Map(a.map(x=>[x.id,x])).values()]}
function startLearning(){startQuiz('learn',poolForDay(),10,true)}
function vocabQuestions(){return D.days[dayNo()-1].terms.map(i=>{let v=D.terms[i],wrong=pick(D.terms.filter(x=>x.id!==v.id),3).map(x=>x.definition),opts=[v.definition,...wrong].sort(()=>Math.random()-.5);return{id:'vq'+v.id,module:v.category,topic:v.topic,subtopic:'Vocabulario',type:'vocabulario',difficulty:'BÁSICO',stem:`¿Cuál es la definición de “${v.term}”?`,options:opts,answer:opts.indexOf(v.definition),explanation:v.explanation}})}
function startQuiz(mode,qs,count,immediate){qs=qs.slice(0,count);session={mode,ids:qs.map(q=>q.id),custom:qs.filter(q=>!D.questions.some(x=>x.id===q.id)),index:0,answers:{},immediate,started:Date.now()};user().session=session;save();renderQuiz()}
function getQs(){return session.ids.map(id=>D.questions.find(q=>q.id===id)||session.custom.find(q=>q.id===id))}
function renderQuiz(){let qs=getQs(),q=qs[session.index],chosen=session.answers[session.index],answered=chosen!==undefined,letters='ABCD';layout(`PREGUNTA ${session.index+1} DE ${qs.length}`,`<div class="progressbar"><span style="width:${(session.index+1)/qs.length*100}%"></span></div>${session.mode==='exam'?`<div class="quiznav">${qs.map((_,i)=>`<button class="${i===session.index?'current':''} ${session.answers[i]!==undefined?'answered':''}" data-jump="${i}">${i+1}</button>`).join('')}</div>`:''}<article class="card"><p><span class="pill">${q.difficulty}</span> · ${q.topic}</p><h2>${q.stem}</h2><div class="options">${q.options.map((o,i)=>`<button class="option ${chosen===i?'selected':''} ${session.immediate&&answered?(i===q.answer?'correct':chosen===i?'wrong':''):''}" data-answer="${i}" ${session.immediate&&answered?'disabled':''}><strong>${letters[i]}.</strong> ${o}</button>`).join('')}</div><div id="feedback">${session.immediate&&answered?feedback(q,chosen===q.answer):session.mode==='exam'&&answered?'<div class="feedback">RESPUESTA GUARDADA ✓</div>':''}</div><div class="toolbar">${answered||!session.immediate?`<button class="btn" id="next">${session.index===qs.length-1?(session.mode==='exam'?'ENTREGAR SIMULACRO':'TERMINAR'):'SIGUIENTE PREGUNTA'}</button>`:''}</div></article>`,'PREGUNTAS Y EVALUACIONES');document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(+b.dataset.answer));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{session.index=+b.dataset.jump;persist();renderQuiz()});let nx=$('#next');if(nx)nx.onclick=()=>advance()}
function feedback(q,ok){return`<div class="feedback ${ok?'':'bad'}"><h3>${ok?'✓ CORRECTO':'✕ INCORRECTO'}</h3><p>${q.explanation}</p><p><strong>Respuesta correcta:</strong> ${q.options[q.answer]}</p><p>El razonamiento importa porque una decisión de ingeniería debe poder justificarse y verificarse.</p></div>`}
function answer(i){let q=getQs()[session.index];session.answers[session.index]=i;if(session.immediate)record(q,i===q.answer);persist();renderQuiz()}
function persist(){user().session=session;save()}
function advance(){let qs=getQs();if(session.index<qs.length-1){session.index++;persist();renderQuiz()}else finishQuiz()}
function finishQuiz(){let qs=getQs(),correct=qs.filter((q,i)=>session.answers[i]===q.answer).length,mode=session.mode;if(mode==='exam'&&Object.keys(session.answers).length<qs.length&&!confirm('Aún hay preguntas pendientes. ¿Deseas entregar?'))return;if(mode==='exam')qs.forEach((q,i)=>record(q,session.answers[i]===q.answer));if(mode==='learn')ds().questions=true;if(mode==='evaluation')ds().evaluation=true;if(mode==='review')ds().review=true;if(mode==='vocab')ds().vocab=true;let result={date:new Date().toISOString(),mode,score:correct,total:qs.length,answers:Object.assign({},session.answers)};if(mode==='exam')user().exams.push(result);user().history.push(result);user().session=null;session=null;save();resultPage(result,qs)}
function resultPage(r,qs){let pct=Math.round(r.score/r.total*100),topics={};qs.forEach((q,i)=>{let t=topics[q.topic]||(topics[q.topic]={a:0,c:0});t.a++;if(q.answer===r.answers[i])t.c++});let detail=Object.entries(topics).map(([t,v])=>`<li>${t}: <strong>${Math.round(v.c/v.a*100)}%</strong> (${v.c}/${v.a})</li>`).join('');let weak=Object.entries(topics).filter(x=>x[1].c/x[1].a<.7).map(x=>x[0]);layout('Resultado',`<section class="hero"><div class="stats">${pct}%</div><h2>${r.score} correctas · ${r.total-r.score} incorrectas</h2><p>${pct>=80?'Buen dominio. Continúa con la ruta.':'Conviene repasar las explicaciones y la cola de repaso.'}</p></section><div class="grid"><article class="card"><h2>Desempeño por tema</h2><ul>${detail}</ul></article><article class="card"><h2>Temas débiles y recomendación</h2><p>${weak.length?weak.join(', ')+' — repásalos desde Mi progreso y la cola de repaso.':'No se detectaron debilidades en esta sesión.'}</p></article></div><p><button class="btn big" data-go="home">VOLVER AL INICIO</button> <button class="btn ghost" data-go="progress">VER MI PROGRESO</button></p>`,'SESIÓN FINALIZADA');bindGo()}
function evaluation(){startQuiz('evaluation',pick(D.questions.filter(q=>q.topic===D.days[dayNo()-1].topic),4),4,true)}
function review(){let qs=dueReviews().map(id=>D.questions.find(q=>q.id===id)).filter(Boolean);if(!qs.length){ds().review=true;save();toast('No hay errores pendientes');home()}else startQuiz('review',qs,Math.min(10,qs.length),true)}
function resume(){session=user().session;renderQuiz()}
function practice(){let mods=[...new Set(D.questions.map(q=>q.module))];layout('Preguntas y evaluaciones',`<div class="grid"><article class="card"><h2>1. APRENDER HOY</h2><p>10 preguntas adaptativas: aproximadamente 60% del tema actual, 25% de errores y 15% de repaso general.</p><button class="btn" id="todayQuiz">APRENDER HOY</button></article><article class="card"><h2>2. PRACTICAR POR TEMA</h2><label>Módulo<select id="module"><option value="">Todos</option>${mods.map(x=>`<option>${x}</option>`).join('')}</select></label><br><label>Dificultad<select id="difficulty"><option value="">Todas</option><option>BÁSICO</option><option>INTERMEDIO</option><option>AVANZADO</option></select></label><p><button class="btn" id="topicQuiz">COMENZAR PRÁCTICA</button></p></article><article class="card"><h2>3. SIMULACRO</h2><p>20 preguntas. La corrección aparece solo al entregar; puedes navegar y volver.</p><button class="btn" id="exam">INICIAR SIMULACRO</button></article></div>`,'ELIGE UN CAMINO');$('#todayQuiz').onclick=startLearning;$('#topicQuiz').onclick=()=>{let m=$('#module').value,d=$('#difficulty').value,p=D.questions.filter(q=>(!m||q.module===m)&&(!d||q.difficulty===d));startQuiz('practice',pick(p,10),10,true)};$('#exam').onclick=()=>startQuiz('exam',pick(D.questions,20),20,false)}
function vocab(){let known=Object.values(user().vocab).filter(x=>x.rating==='known').length;layout('Vocabulario',`<p>${known} de ${D.terms.length} términos marcados como aprendidos.</p><div class="grid">${D.terms.map(v=>`<article class="card"><p class="eyebrow">${v.category}</p><h3>${v.term}</h3><p>${v.definition}</p><p><strong>Ejemplo:</strong> ${v.example}</p><button class="btn ghost speak" data-text="${esc(v.term+'. '+v.definition)}">🔊 ESCUCHAR</button></article>`).join('')}</div><button class="btn" id="vocabTest">EVALUACIÓN DE VOCABULARIO</button>`,'DICCIONARIO ESPECIALIZADO');document.querySelectorAll('.speak').forEach(b=>b.onclick=()=>speechSynthesis.speak(new SpeechSynthesisUtterance(b.dataset.text)));$('#vocabTest').onclick=()=>startQuiz('vocab',pick(D.terms,10).map(v=>{let wrong=pick(D.terms.filter(x=>x.id!==v.id),3).map(x=>x.definition),o=[v.definition,...wrong].sort(()=>Math.random()-.5);return{id:'all'+v.id,module:v.category,topic:v.topic,subtopic:'Vocabulario',type:'vocabulario',difficulty:'BÁSICO',stem:`¿Qué significa “${v.term}”?`,options:o,answer:o.indexOf(v.definition),explanation:v.explanation}}),10,true)}
function calendar(){let today=dayNo();layout('PLAN DE 180 DÍAS',`<p><span class="pill">HOY: día ${today}</span> Puedes consultar cualquier día; el inicio siempre te conduce al día correspondiente por fecha.</p><div class="calendar">${D.days.map(d=>{let s=user().days[d.day],state=s&&completed(s)?'Completado':s&&Object.values(s).some(Boolean)?'En progreso':'Pendiente',date=new Date(user().start+'T00:00:00');date.setDate(date.getDate()+d.day-1);return`<button class="day ${d.day===today?'today':''} ${state==='Completado'?'done':''}" data-day="${d.day}"><strong>Día ${d.day}${d.day===today?' · HOY':''}</strong><small>${date.toLocaleDateString('es')}</small><br><span>${d.topic}</span><br><span class="pill">${state}</span></button>`}).join('')}</div>`,'CALENDARIO');document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>dayPreview(+b.dataset.day))}
function dayPreview(n){let d=D.days[n-1],s=user().days[n]||{};layout(`Día ${n}: ${d.topic}`,`<article class="card"><p class="eyebrow">${d.phase}</p><p>${d.subtopic}</p><p><strong>Módulo:</strong> ${d.module} · <strong>Nivel:</strong> ${d.difficulty}</p><ul><li>${s.vocab?'✓':'○'} Vocabulario</li><li>${s.lesson?'✓':'○'} Lección</li><li>${s.questions?'✓':'○'} Preguntas</li><li>${s.evaluation?'✓':'○'} Evaluación</li></ul></article><p><button class="btn ghost" data-go="calendar">VOLVER AL PLAN</button>${n===dayNo()?' <button class="btn" data-go="home">ESTUDIAR HOY</button>':''}</p>`,'CONSULTA DEL PLAN');bindGo()}
function progress(){let u=user(),pct=u.stats.answered?Math.round(u.stats.correct/u.stats.answered*100):0,done=Object.values(u.days).filter(completed).length,topics=Object.entries(u.stats.byTopic).sort((a,b)=>(b[1].c/b[1].a)-(a[1].c/a[1].a)),weak=topics.filter(x=>x[1].a>=2&&x[1].c/x[1].a<.7).map(x=>x[0]),strong=topics.filter(x=>x[1].a>=2&&x[1].c/x[1].a>=.8).map(x=>x[0]);let dates=new Set(u.history.map(x=>x.date.slice(0,10)));let streak=0,x=new Date();while(dates.has(x.toISOString().slice(0,10))){streak++;x.setDate(x.getDate()-1)}layout('MI PROGRESO',`<div class="grid"><article class="card"><div class="stats">${dayNo()} / 180</div><p>Día actual</p></article><article class="card"><div class="stats">${done}</div><p>Días completados</p></article><article class="card"><div class="stats">${u.stats.answered}</div><p>Preguntas contestadas</p></article><article class="card"><div class="stats">${pct}%</div><p>Precisión</p></article><article class="card"><div class="stats">${dueReviews().length}</div><p>Repasos pendientes</p></article><article class="card"><div class="stats">${Object.values(u.vocab).filter(v=>v.rating==='known').length}</div><p>Vocabulario dominado</p></article><article class="card"><div class="stats">${u.exams.length}</div><p>Simulacros realizados</p></article><article class="card"><div class="stats">${streak}</div><p>Racha de estudio</p></article></div><div class="grid"><article class="card"><h2>Temas fuertes</h2><p>${strong.join(', ')||'Aún recopilando datos.'}</p><h2>Temas débiles</h2><p>${weak.join(', ')||'Ninguno detectado todavía.'}</p></article><article class="card"><h2>Desempeño por tema</h2>${topics.map(([t,v])=>`<div class="barrow"><header><span>${t}</span><strong>${Math.round(v.c/v.a*100)}%</strong></header><div class="progressbar"><span style="width:${v.c/v.a*100}%"></span></div></div>`).join('')||'<p>Responde preguntas para ver resultados.</p>'}</article><article class="card"><h2>Resultados de simulacros</h2>${u.exams.slice(-5).reverse().map(e=>`<p>${new Date(e.date).toLocaleDateString('es')}: <strong>${e.score}/${e.total}</strong></p>`).join('')||'<p>Aún no realizaste simulacros.</p>'}<h2>Evaluaciones</h2><p>${u.history.filter(x=>x.mode==='evaluation').length} realizadas</p></article></div>`,'ESTADÍSTICAS PERSONALES')}
function sources(){layout('Fuentes y alcance',`<article class="card"><p><strong>Contenido de referencia:</strong> la ruta se organizó contrastando competencias profesionales y guías públicas oficiales. No existe un único temario regulado universal de ingeniería de datos.</p><ul><li><a href="https://sfia-online.org/en/sfia-9/skills/data-engineering" target="_blank" rel="noreferrer">SFIA 9 · Data engineering</a></li><li><a href="https://csed.acm.org/" target="_blank" rel="noreferrer">ACM/IEEE-CS/AAAI Computer Science Curricula 2023</a></li><li><a href="https://cloud.google.com/learn/certification/data-engineer" target="_blank" rel="noreferrer">Google Cloud Professional Data Engineer</a></li><li><a href="https://aws.amazon.com/certification/certified-data-engineer-associate/" target="_blank" rel="noreferrer">AWS Certified Data Engineer – Associate</a></li><li><a href="https://learn.microsoft.com/credentials/certifications/azure-data-engineer/" target="_blank" rel="noreferrer">Microsoft Learn · Azure Data Engineer</a></li></ul><p><strong>Contenido educativo:</strong> las lecciones, síntesis y secuencia fueron creadas para esta guía.</p><p><strong>Práctica:</strong> todas las preguntas son ejercicios originales; no son preguntas oficiales ni reproducen exámenes.</p></article>`,'TRANSPARENCIA')}
function bindGo(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go))}
function go(x){if(!ensure())return;({home,practice,vocab,calendar,progress,lesson,vocabDaily,startLearning:()=>startLearning(),learn:()=>startLearning(),evaluation,review,sources}[x]||home)()}
document.addEventListener('click',e=>{let b=e.target.closest('[data-go]');if(b){e.preventDefault();go(b.dataset.go)}});$('#usersBtn').onclick=()=>users();window.addEventListener('beforeunload',()=>{if(active)save()});if(active)home();else users(true);
})();
